# the upstream component nginx needs to connect to
upstream django_main {
    server unix:/run/gunicorn/main.sock fail_timeout=30s;
}

server {
    listen 80 default_server;

    server_tokens off;

    # Locations
    include locations.conf;

    # Error pages
    include errors.conf;
}
