# the upstream component nginx needs to connect to
upstream django_main {
    server unix:/run/gunicorn/main.sock fail_timeout=30s;
}

server {
    listen 80 default_server;

    server_tokens off;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;

    server_tokens off;

    # SSL configuration.
    # Create it manually from ssl.conf.template before
    # bringing the application up with HTTPS enabled.
    include ssl.conf;

    # Locations
    include locations.conf;

    # Error pages
    include errors.conf;
}
