# the upstream component nginx needs to connect to
upstream django_main {
    server unix:/run/gunicorn/main.sock fail_timeout=30s;
}

server {
    listen 80;
    server_name localhost;

    server_tokens off;

    # Locations
    include locations.conf;

    location /static/ {
        alias /var/www/static/;
    }

    location ^~/admin {
        uwsgi_pass                  django_main;
        uwsgi_pass_header           Authorization;
        uwsgi_pass_request_headers  on;
        uwsgi_read_timeout          45;
        include                     uwsgi_params;
        uwsgi_param                 HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        client_max_body_size        20m;
    }

    location ~^/api/feeds {
        uwsgi_pass                  django_main;
        uwsgi_pass_header           Authorization;
        uwsgi_pass_request_headers  on;
        uwsgi_read_timeout          600;
        uwsgi_buffering             off;
        include                     uwsgi_params;
        uwsgi_param                 HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;

        gzip on;
        gzip_types application/json;
        gzip_min_length 1000;
    }

    location / {
        uwsgi_pass                  django_main;
        uwsgi_pass_header           Authorization;
        uwsgi_pass_request_headers  on;
        uwsgi_read_timeout          45;
        include                     uwsgi_params;
        uwsgi_param                 HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
        client_max_body_size        20m;
    }

    # Error pages
    include errors.conf;

}