uwsgi_pass_header           Authorization;
uwsgi_pass_request_headers  on;
uwsgi_read_timeout          45;
include                     uwsgi_params;
uwsgi_param                 HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
client_max_body_size        100m;

location = /hc {
    return                  200;
}

location = /favicon.ico {
    access_log              off;
    log_not_found           off;
}

location /static/ {
    alias                   /var/www/static/;
    add_header              Cache-Control "public, max-age=3600";

    gzip                    on;
    gzip_vary               on;
    gzip_min_length         1000;
    gzip_types              text/css text/javascript application/javascript application/json image/svg+xml;
}

location / {
    uwsgi_pass              django_main;
}

location ~^/api/feeds {
    uwsgi_pass              django_main;
    uwsgi_read_timeout      600;

    gzip                    on;
    gzip_vary               on;
    gzip_min_length         1000;
    gzip_types              application/json application/x-ndjson text/csv text/plain;
}
