FROM library/nginx:1.31.3-alpine

ENV NGINX_LOG_DIR=/var/log/nginx

RUN apk add --no-cache bash

# this is to avoid having logs redirected to stdout/stderr
RUN mkdir -p /var/cache/nginx \
	&& rm $NGINX_LOG_DIR/access.log $NGINX_LOG_DIR/error.log \
	&& touch $NGINX_LOG_DIR/access.log $NGINX_LOG_DIR/error.log

VOLUME $NGINX_LOG_DIR