services:
  app:
    image: ghcr.io/greedybear-project/greedybear:stag

  nginx:
    image: ghcr.io/greedybear-project/greedybear_nginx:stag

  qcluster:
    image: ghcr.io/greedybear-project/greedybear:stag