# you have to populate the ENV variable REACT_APP_INTELOWL_VERSION in the .env file to have this work
services:
  app:
    image: ghcr.io/greedybear-project/greedybear:${REACT_APP_INTELOWL_VERSION}

  nginx:
    image: ghcr.io/greedybear-project/greedybear_nginx:${REACT_APP_INTELOWL_VERSION}

  celery_beat:
    image: ghcr.io/greedybear-project/greedybear:${REACT_APP_INTELOWL_VERSION}

  celery_worker_default:
    image: ghcr.io/greedybear-project/greedybear:${REACT_APP_INTELOWL_VERSION}

  qcluster:
    image: ghcr.io/greedybear-project/greedybear:${REACT_APP_INTELOWL_VERSION}