# Generated by Django 5.2.14 on 2026-05-25 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0053_deduplicate_ioc_identity_and_add_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attackeractivitybucket',
            new_name='greedybear__bucket__2b228d_idx',
            old_name='greedybear__bucket__ce4aaf_idx',
        ),
        migrations.RenameIndex(
            model_name='attackeractivitybucket',
            new_name='greedybear__feed_ty_07027f_idx',
            old_name='greedybear__feed_ty_84e90b_idx',
        ),
        migrations.RenameIndex(
            model_name='attackeractivitybucket',
            new_name='greedybear__attacke_963f74_idx',
            old_name='greedybear__attacke_910f2f_idx',
        ),
    ]
