# Generated by Django 5.2.13 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greedybear", "0055_sensor_autonomous_system_sensor_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ioc",
            name="greedybear__attacke_2b9c7d_idx",
        ),
        migrations.AddIndex(
            model_name="ioc",
            index=models.Index(fields=["last_seen"], name="greedybear_ioc_last_seen_idx"),
        ),
    ]
