# Generated by Django 5.2.13 on 2026-05-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0056_ioc_last_seen_index_and_drop_attacker_country_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ioc',
            new_name='greedybear__last_se_567d25_idx',
            old_name='greedybear_ioc_last_seen_idx',
        ),
        migrations.AddField(
            model_name='sensor',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(condition=models.Q(('api_source__isnull', False)), fields=('api_source', 'address'), name='unique_sensor_per_api_source'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(condition=models.Q(('api_source__isnull', True)), fields=('address',), name='unique_internal_sensor_address'),
        ),
    ]
