# Generated by Django 5.2.13 on 2026-05-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0057_rename_greedybear_ioc_last_seen_idx_greedybear__last_se_567d25_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ioc_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('api_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_statuses', to='greedybear.apisource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('event_type', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('token_id', models.CharField(blank=True, default='', max_length=100)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dest_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, default='', max_length=50)),
                ('service_name', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('related_url', models.URLField(blank=True, default='', max_length=900)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('command', models.TextField(blank=True, default='')),
                ('cve_id', models.CharField(blank=True, default='', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('api_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='greedybear.apisource')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='greedybear.eventstatus')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='greedybear.sensor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eventstatus',
            index=models.Index(fields=['task_id'], name='greedybear__task_id_74e8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstatus',
            index=models.Index(fields=['status'], name='greedybear__status_672acb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventstatus',
            index=models.Index(fields=['api_source', 'status'], name='greedybear__api_sou_daf980_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['src_ip'], name='greedybear__src_ip_bae8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['timestamp'], name='greedybear__timesta_b80eba_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['sensor'], name='greedybear__sensor__8d5e87_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['processed'], name='greedybear__process_381f44_idx'),
        ),
    ]
