# Generated by Django 5.2.14 on 2026-06-26 15:49

import greedybear.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0058_eventstatus_rawevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_file', models.FileField(blank=True, null=True, storage=greedybear.storage.QuarantineStorage(), upload_to='')),
                ('md5', models.CharField(blank=True, default='', max_length=32)),
                ('sha1', models.CharField(blank=True, default='', max_length=40)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('locator', models.CharField(blank=True, default='', max_length=1024)),
                ('mtime', models.FloatField(blank=True, null=True)),
                ('cowrie_sessions', models.ManyToManyField(blank=True, related_name='payloads', to='greedybear.cowriesession')),
                ('iocs', models.ManyToManyField(blank=True, related_name='payloads', to='greedybear.ioc')),
                ('source_honeypots', models.ManyToManyField(blank=True, to='greedybear.honeypot')),
            ],
        ),
    ]
