# Generated by Django 5.2.14 on 2026-06-20 19:32

import django.db.models.deletion
import greedybear.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0058_eventstatus_rawevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_file', models.FileField(blank=True, null=True, storage=greedybear.storage.QuarantineStorage(), upload_to='')),
                ('md5', models.CharField(blank=True, default='', max_length=32)),
                ('sha1', models.CharField(blank=True, default='', max_length=40)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('mime_type', models.CharField(blank=True, default='', max_length=32)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('locator', models.CharField(blank=True, default='', max_length=1024)),
                ('mtime', models.FloatField(blank=True, null=True)),
                ('cowrie_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payloads', to='greedybear.cowriesession')),
                ('ioc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payloads', to='greedybear.ioc')),
                ('source_honeypot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='greedybear.honeypot')),
            ],
        ),
    ]
