# Generated by Django 5.2.16 on 2026-07-21 08:55

import django.contrib.postgres.fields
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0059_honeypotpayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='cves',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='ioc',
            name='protocols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='honeypotpayload',
            name='sha256',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='honeypotpayload',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sha256'), name='unique_honeypotpayload_sha256_lower'),
        ),
    ]
