# Generated by Django 5.2.13 on 2026-08-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0059_dashboardconfig'),
        ('greedybear', '0060_ioc_cves_ioc_protocols_alter_honeypotpayload_sha256_and_more'),
    ]

    operations = [
    ]
