# Generated by Django 5.2.16 on 2026-07-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0060_ioc_cves_ioc_protocols_alter_honeypotpayload_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypotpayload',
            name='is_uploaded_mb',
            field=models.BooleanField(db_index=True, default=False, help_text='True once the payload has been successfully reported to MalwareBazaar (or confirmed as a duplicate there).'),
        ),
    ]
