# Generated by Django 5.2.17 on 2026-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0062_dashboardconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
