# Generated by Django 5.2.16 on 2026-09-16 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0062_dashboardconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='http_attack_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), blank=True, default=list, size=None),
        ),
    ]
