# Generated by Django 5.2.17 on 2026-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0066_migrate_tanner_attack_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='protocol',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
