# Generated by Django 5.2.17 on 2026-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0067_alter_credential_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='high_credential_reuse',
            field=models.BooleanField(default=False),
        ),
    ]
