# Generated by Django 5.2.17 on 2026-10-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0069_migrate_credential_reuse_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(choices=[('extraction', 'Extraction'), ('payload_extraction', 'Payload extraction')], max_length=32)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed_retryable', 'Failed (retryable)'), ('failed_permanent', 'Failed (permanent)')], default='running', max_length=20)),
                ('ioc_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_name', 'window_end'], name='greedybear__job_nam_e42af7_idx')],
            },
        ),
    ]
