# Generated by Django 5.2.17 on 2026-10-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greedybear', '0070_migrate_firehol_categories_to_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioc',
            name='firehol_categories',
        ),
    ]
